Add `-C panic=abort` flag to rustc for device build
We ran into similar issue for linux_bionic target earlier. This fix is similar to aosp/2423768.

In `libstd` (`rust_toolchain_library`) [1], we explicitly prefer libpanic_abort over libpanic_unwind for android target. However, the rustc flag wasn't set to reflect it.

[1] https://cs.android.com/android/platform/superproject/main/+/main:prebuilts/rust/Android.bp;l=506-508;drc=f459ab789684da92bc8a4caae1c55e07931e975c

I found this issue in Bazel build because `libstd`'s deps are correctly sandboxed and yields the error

```
error[E0463]: can't find crate for `panic_unwind`
```

Test: CI
Bug: 295918553
Change-Id: Ic4b4225ae2411519ce206d28c8d556098caf8824