Update patch set 5
Patch Set 5:

The CL failed to apply on some of the builds targets:

CherryPickError: Changes failed to apply, merge conflict detected. See git.log here https://android-build.googleplex.com/builds/pending/P13306251/apps/latest
,
 error: Changes failed to apply, merge conflict detected. See git.log here https://android-build.googleplex.com/builds/pending/P13306251/apps/latest

Rebasing and retrying

Patch-set: 5
Reviewer: Gerrit User 1124149 <1124149@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0