Update patch set 1
Patch Set 1:

check for ctx.clang() is necessary because of

error: system/core/libcutils/Android.bp:50:1: module "libcutils" variant "windows_x86_static": Use of sanitizers requires clang

Patch-set: 1