Revert "rustc-1.70.0 Build 10322039"
Revert submission 2627434-rust-update-prebuilts-1.70.0

Reason for revert: broke aosp_riscv64-userdebug build as:

  error: internal compiler error: 
    compiler/rustc_codegen_llvm/src/context.rs:188:13:
    data-layout for target `riscv64-linux-android`,
    `e-m:e-p:64:64-i64:64-i128:128-n64-S128`, differs from LLVM
    target's `riscv64-linux-android` default layout,
    `e-m:e-p:64:64-i64:64-i128:128-n32:64-S128`

Reverted changes: /q/submissionid:2627434-rust-update-prebuilts-1.70.0

Change-Id: Ia95aaa83beef6eb790f0a40a4614ee9204d57221