Pass -nostdlibinc to bindgen.
On my machine, all builds are failing like this:

/usr/include/bits/types/mbstate_t.h:6:21: error: typedef redefinition with different types ('__mbstate_t' vs 'struct mbstate_t')
bionic/libc/include/bits/mbstate_t.h:47:3: note: previous definition is here
Bindgen unexpectedly panicked
This may be caused by one of the known-unsupported things (https://rust-lang.github.io/rust-bindgen/cpp.html), please modify the bindgen flags to work around it as described in https://rust-lang.github.io/rust-bindgen/cpp.html
Otherwise, please file an issue at https://github.com/rust-lang/rust-bindgen/issues/new
panicked at external/rust/android-crates-io/crates/bindgen-cli/main.rs:52:36:
Unable to generate bindings: ClangDiagnostic("/usr/include/bits/types/mbstate_t.h:6:21: error: typedef redefinition with different types ('__mbstate_t' vs 'struct mbstate_t')\n")

This seems to be caused by /usr/include being on the include path. It's
unclear why CI doesn't seem to be affected, maybe the /usr/include
contents in CI don't trigger this issue. Regardless, /usr/include
shouldn't be on the include path so add -nostdlibinc to the bindgen
command line.

Change-Id: I32c0d6e49f96d7341349845bf8891dc6afeb366c