Update patch set 1
Patch Set 1:

https://android-review.googlesource.com/370692
https://android-review.googlesource.com/230951
https://android-review.googlesource.com/371432
Note that the last patch probably won't be merged because it deviates from upstream, but I could not get the NDK cpufeatures static library to be linked in Android.bp
I got this error: error: external/webp/src/Android.bp:106:1: "libwebp-decode" depends on undefined module "cpufeatures"
error: external/webp/src/Android.bp:16:1: "libwebp-encode" depends on undefined module "cpufeatures"

Patch-set: 1
Reviewer: Gerrit User 1021512 <1021512@85c56323-6fa9-3386-8a01-6480fb634889>