Update pre-opt for conditionally opting libraries.
wrt libs:
android.hidl.base-V1.0-java
android.hidl.manager-V1.0-java

These used to be on the boot classpath, but are half published because
of 1414929, and so the libs were removed in 86259915. However, because
they are added to all apps (and only a relatively small number of apps
use these libraries), this causes a ~21ms regression in <= P targeting
apps' startup times. Now, they can be specified to only be added to
specific apps.

Bug: 86259915
Test: grepping for java.lang.NoClassDefFoundError in logs for relevant
    apps w/ and w/o whitelist applied
Change-Id: Iab39d030dcdc0334d3baa05772d18216692a8c56