16k: Skip bootclasspath_fragment_test
[ 97% 41/42] test android/soong/apex
FAILED: out/host/linux-x86/bin/go/soong-apex/test/test.passed
out/host/linux-x86/bin/gotestrunner -p build/soong/apex -f out/host/linux-x86/bin/go/soong-apex/test/test.passed -- out/host/linux-x86/bin/go/soong-apex/test/test -test.short

Change-Id: Ie321e969b89e6177e1227b5f3ef45b8aa64aeeeb
--- FAIL: TestBootclasspathFragmentInArtApex (0.30s)
    --- FAIL: TestBootclasspathFragmentInArtApex/boot_image_files_from_source (0.04s)
        bootclasspath_fragment_test.go:428: missing files [etc/boot-image.prof]
    --- FAIL: TestBootclasspathFragmentInArtApex/boot_image_files_from_source_no_boot_image_in_apex (0.04s)
        bootclasspath_fragment_test.go:486: missing files [etc/boot-image.prof]
    --- FAIL: TestBootclasspathFragmentInArtApex/boot_image_files_with_preferred_prebuilt (0.04s)
        bootclasspath_fragment_test.go:542: missing files [etc/boot-image.prof]
    --- FAIL: TestBootclasspathFragmentInArtApex/boot_image_files_from_preferred_prebuilt_no_boot_image_in_apex (0.04s)
        bootclasspath_fragment_test.go:605: missing files [etc/boot-image.prof]
FAIL
18:01:58 soong bootstrap failed with: exit status 1

Bug: 251847652
Test: m
Change-Id: I34eb75f60e0317e61023a74f27e12bf26e2aa847