Update patch set 4
Patch Set 4:

There's one TH error that is rather stubborn. I can't see how it relates to my change, and I get that same error locally on a pristine freshly synced git_master tree:

$ build/soong/soong_ui.bash --make-mode TARGET_PRODUCT=taimen TARGET_BUILD_VARIANT=userdebug WITH_TIDY=1 out/soong/.intermediates/bionic/tests/libfortify1-tests-clang/android_arm64_armv8-a_cortex-a73_static/obj/bionic/tests/fortify_test_main.tidy
/.../
Error while processing /usr/local/google/home/mast/android/internal/bionic/tests/fortify_test_main.cpp.
bionic/tests/fortify_test.cpp:937:60: error: use of undeclared identifier '__bos0' [clang-diagnostic-error]
  __builtin___mempcpy_chk(buf2, input_str, input_str_size, __bos0(buf2));
                                                           ^
bionic/tests/fortify_test.cpp:942:80: error: use of undeclared identifier '__bos0' [clang-diagnostic-error]
  void *fortify_ptr = __builtin___mempcpy_chk(buf1, input_str, input_str_size, __bos0(buf2));
                                                                               ^
Suppressed 859 warnings (843 in non-user code, 16 NOLINT).
Use -header-filter=.* to display errors from all non-system headers. Use -system-headers to display errors from
 system headers as well.
Found compiler error(s).

Given this I wonder how it stays green on ab/, e.g. https://android-build.googleplex.com/builds/submitted/6438723/taimen-userdebug/latest. Is the error hidden due to incremental builds?

Patch-set: 4
Reviewer: Gerrit User 1373864 <1373864@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0