Update patch set 3
Change has been successfully merged

2 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: apex/apex.go
Insertions: 2, Deletions: 2.

@@ -2771,11 +2771,11 @@
 		// Let's give some hint for apex_available
 		hint := fmt.Sprintf("%q", apexName)
 
-		if strings.HasPrefix(apexName, "com.") && !strings.HasPrefix(apexName, "com.android.") {
+		if strings.HasPrefix(apexName, "com.") && !strings.HasPrefix(apexName, "com.android.") && strings.Count(apexName, ".") >= 2 {
 			// In case of a partner APEX, prefix format might be an option.
 			components := strings.Split(apexName, ".")
 			components[len(components)-1] = "*"
-			hint += fmt.Sprintf("or %q", strings.Join(components, "."))
+			hint += fmt.Sprintf(" or %q", strings.Join(components, "."))
 		}
 
 		ctx.ModuleErrorf("%q requires %q that doesn't list the APEX under 'apex_available'."+
```
```
The name of the file: android/apex.go
Insertions: 3, Deletions: 0.

@@ -549,6 +549,9 @@
 			if strings.Count(n, ".") < 2 {
 				mctx.PropertyErrorf("apex_available", "Wildcard requires two or more components like com.foo.*")
 			}
+			if strings.Count(n, "*") != 1 {
+				mctx.PropertyErrorf("apex_available", "Wildcard is not allowed in the middle.")
+			}
 			continue
 		}
 		if !mctx.OtherModuleExists(n) && !mctx.Config().AllowMissingDependencies() {
```
```
The name of the file: apex/apex_test.go
Insertions: 30, Deletions: 0.

@@ -6748,6 +6748,16 @@
 			apexAvailable: "com.*.foo",
 			expectedError: "should end with .*",
 		},
+		{
+			name:          "wildcard in the middle",
+			apexAvailable: "com.foo*.*",
+			expectedError: "not allowed in the middle",
+		},
+		{
+			name:          "hint with prefix pattern",
+			apexAvailable: "//apex_available:platform",
+			expectedError: "Consider adding \"com.foo.bar\" or \"com.foo.*\"",
+		},
 	} {
 		t.Run(tc.name, func(t *testing.T) {
 			errorHandler := android.FixtureExpectsNoErrors
@@ -6783,6 +6793,26 @@
 				}`)
 		})
 	}
+	testApexError(t, `Consider adding "com.foo" to`, `
+		apex {
+			name: "com.foo", // too short for a partner apex
+			key: "myapex.key",
+			native_shared_libs: ["libfoo"],
+			updatable: false,
+		}
+
+		apex_key {
+			name: "myapex.key",
+			public_key: "testkey.avbpubkey",
+			private_key: "testkey.pem",
+		}
+
+		cc_library {
+			name: "libfoo",
+			stl: "none",
+			system_shared_libs: [],
+		}
+	`)
 }
 
 func TestOverrideApex(t *testing.T) {
```


Patch-set: 3
Status: merged
Tag: autogenerated:gerrit:merged
Reviewer: Gerrit User 1974282 <1974282@85c56323-6fa9-3386-8a01-6480fb634889>
Label: SUBM=+1, 11136f74917a7d3682c01881f64153b72d224e69
Submission-id: 3223005
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Build-Team-Review
Submitted-with: MAY: Code-Review: Gerrit User 1535516 <1535516@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Open-Source-Licensing: Gerrit User 1757831 <1757831@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Lint: Gerrit User 1757831 <1757831@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: API-Review
Submitted-with: MAY: NDK-API-Review
Submitted-with: MAY: AIDL-API-Review
Submitted-with: MAY: Global-Approval
Submitted-with: MAY: Exempt
Submitted-with: MAY: Performance: Gerrit User 2052902 <2052902@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Autosubmit: Gerrit User 1415877 <1415877@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Presubmit-Ready
Submitted-with: MAY: Presubmit-Verified: Gerrit User 2025861 <2025861@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Bypass-Presubmit
Submitted-with: MAY: Presubmit-Verified-Together
Submitted-with: MAY: Qualcomm-Review
Submitted-with: MAY: Build-Cop-Override
Submitted-with: MAY: DrNo-Review
Submitted-with: OK
Submitted-with: Rule-Name: Code-Owners
Attention: {"person_ident":"Gerrit User 1535516 \u003c1535516@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1415877 \u003c1415877@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}