Make sure cortex-{a53,a73} uses armv7-a.
I'm seeing this breakage since the cortex-a53 flags were
added to soong:

cts/tests/tests/os/jni/android_os_cts_CpuInstructions.cpp:88:20:
error: instruction requires: armv7 or earlier
    asm volatile ( "swp r0, r0, [%0]" : "+r"(ptr) : : "r0" );

I guess armv8-a is the default for arm-linux-androideabi now,
or -mcpu=cortex-a53 turns it on, but I guess this isn't what
is wanted for Android.

Change-Id: I83bde507b585160fdbf5041f324c58a8e86fb464