Example of protobuf issue with pkg_path
When using pkg_path at least 2 levels deepon a
python binary with protos, you get:

Traceback (most recent call last):
  File "/tmp/Soong.python_9xq190aq/mylib/main.py", line 6, in <module>
    import mylib.proto.test_pb2 as test_pb2
  File "/tmp/Soong.python_9xq190aq/mylib/proto/test_pb2.py", line 16, in <module>
    from proto import common_pb2 as proto_dot_common__pb2
ModuleNotFoundError: No module named 'proto'

This issue will also happen with a pkg_path only 1
level deep once we change the PYTHONPATH to only import
the root directory of the zip file, instead of also
importing all the subdirectories of that root directory.

Change-Id: I0169e02e64d84b328e151d8d49b3a6efcff25e40