Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > > Patch Set 1:
> > > 
> > > > Patch Set 1:
> > > > 
> > > > Is this going to be used anywhere outside of bionic?  If it is only for that one library, maybe it would be better to do it with two modules in bionic/libc/Android.bp and a cc_genrule to generate the symbol ordering file from the first to use for the second?
> > > 
> > > I actually tried that in my first attempt at this problem, but it looks like genrule doesn't support the concept of variants, and therefore we are getting an error about missing variant.
> > 
> > Did you try with a genrule or a cc_genrule?
> 
> Oh you are right. That was a genrule. I wasn't aware of cc_genrule. I'll give that a try. Thanks!

cc_genrule doesn't work either, because it's missing the "link" tag in its variant:

error: bionic/libc/Android.bp:1678:1: dependency "libc_unsorted" of "libc.symbol_ordering" missing variant:
  arch:android_x86, image:core, version:
available variants:
  arch:android_native_bridge_arm_armv7-a-neon, image:core, link:shared, version:
  arch:android_native_bridge_arm_armv7-a-neon, image:core, link:shared, version:10000
  arch:android_x86, image:core, link:shared, version:
  arch:android_x86, image:core, link:shared, version:10000
  arch:android_x86, image:recovery, link:shared
  arch:linux_glibc_x86, link:shared, version:
  arch:linux_glibc_x86, link:shared, version:10000
  arch:linux_glibc_x86_64, link:shared, version:
  arch:linux_glibc_x86_64, link:shared, version:10000
  arch:windows_x86, link:shared, version:
  arch:windows_x86, link:shared, version:10000
  arch:windows_x86_64, link:shared, version:
  arch:windows_x86_64, link:shared, version:10000

Patch-set: 1
Reviewer: Gerrit User 1349653 <1349653@85c56323-6fa9-3386-8a01-6480fb634889>