Update patch set 4
Patch Set 4:

+phaulos

the build breakage is this:

  external/deqp/framework/delibs/debase/deString.c:181:9: error: implicit declaration of function 'strnlen_s' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        return strnlen_s(string, maxSize);
               ^

caused by

  #if ((DE_COMPILER == DE_COMPILER_MSC) && (DE_OS != DE_OS_WINCE)) || (defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201100L))
  // ...code that assumes anyone's actually implemented strnlen_s

afaik _no_ C library other than Microsoft's implements _any_ of C11 Annex L, so i think we should just remove the "|| ..." part of this line. (certainly Android, Linux, and Mac OS don't have any of this.)

note also, even for C11 implementations that do implement Annex L:

  As with all bounds-checked functions, strnlen_s is only guaranteed to be available if __STDC_LIB_EXT1__ is defined by the implementation and if the user defines __STDC_WANT_LIB_EXT1__ to the integer constant 1 before including string.h.

but perhaps more importantly, strlen_s is the same function as the POSIX.2008 strnlen(3). so we might also want to replace the #else part with a call to strnlen(3) rather than an unoptimized hand-written implementation.

Patch-set: 4