Update patch set 1
Patch Set 1:

This broke ART buildbot:

FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: build/soong/Android.bp:438:11: module "libwinpthread" variant "windows_x86_static": notice: module providing notice must produce exactly one file

Patch-set: 1
CC: Gerrit User 1018108 <1018108@85c56323-6fa9-3386-8a01-6480fb634889>