Update patch set 2
Patch Set 2:

This should probably end up wrapped with cc_system_library or something so that the linux_libc.link files can just be generated, and not installed.

This *usually* works on a aosp-build-tools checkout that's just building linux host tools, but sometimes hits the missing dependencies check for some reason (and because it's a smaller tree that needs allow_missing_dependencies, it's harder to figure out why).

I'm running into this problem on a full tree:

error: bionic/libc/Android.bp:1615:1: failed to find variation "static" for module "prebuilt_libc" needed by "libc"
error: bionic/libm/Android.bp:6:1: failed to find variation "static" for module "prebuilt_libm" needed by "libm"

Any ideas?

Patch-set: 2
Reviewer: Gerrit User 1074628 <1074628@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=0