Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> looking at the build errors, the uses of libbinder all seem header only deps, which we don't want to be bothered with.

What do you mean by "don't want to be bothered with"? Do you mean that it should not require the "com.android.media.swcodec" apex to be added to libbinder's apex_available property?

Here is the dependency path (might not be the only one) that caused libbinder to be considered as part of the "com.android.media.swcodec". Where is the header only deps linkage in it?

error: frameworks/av/apex/Android.bp:113:1: module "com.android.media.swcodec" variant "android_common_cfi_com.android.media.swcodec_image": "libaudioutils" requires "libspeexresampler" that is not available for the APEX. Dependency path:
    -> mediaswcodec{os:android,image:vendor.R,arch:arm64_armv8-a,version:,cfi:cfi,apex:com.android.media.swcodec}
    -> libmedia_codecserviceregistrant{os:android,image:vendor.R,arch:arm64_armv8-a,link:shared,version:,cfi:cfi,apex:com.android.media.swcodec}
    -> libcodec2_soft_flacdec{os:android,image:vendor.R,arch:arm64_armv8-a,link:shared,version:,cfi:cfi,apex:com.android.media.swcodec}
    -> libstagefright_flacdec{os:android,image:vendor.R,arch:arm64_armv8-a,link:shared,version:,cfi:cfi,apex:com.android.media.swcodec}
    -> libstagefright_flacdec{os:android,image:vendor.R,arch:arm64_armv8-a,link:static,version:,cfi:cfi,apex:com.android.media.swcodec}
    -> libaudioutils{os:android,image:vendor.R,arch:arm64_armv8-a,link:static,version:,cfi:cfi,apex:com.android.media.swcodec}
    -> libspeexresampler{os:android,image:vendor.R,arch:arm64_armv8-a,link:shared,version:,apex:com.android.media.swcodec}

Patch-set: 1
Reviewer: Gerrit User 1039338 <1039338@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0