Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > > Patch Set 4:
> >  > 
> >  >  > Patch Set 4: Verified+1 Code-Review+1
> >  >  >  
> >  >  > Verified that mcpu=cortex-a53 is used only for toolchain libaries
> >  >  >  
> >  >  > How am I supposed to send this to master? 
> >  > 
> >  > Yup, please upload to master first. (we'll loop related reviewers there).
> >  > 
> >  >  > push this change and push the revert as well?
> >  > I thought only this change (fallback to a53 for gcc) will be enough, no?
> > 
> > It's enough but since master isn't affected, 
> 
> Not sure why master isn't affected.
> I just tried `arm-linux-androideabi-gcc-4.9 -mcpu=cortex-a55 test.c` and it replies:
> 
> error: unrecognized argument in option '-mcpu=cortex-a55'
> 
> Please CMIIW.

Sorry you're right, we pulled only the binutils change to support cortex-a55 but not the gcc one https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=0bf57487e7aeb4794d513e9d124c75cc707c65c7
Will add that to commit message for clarity, thanks

Patch-set: 4
Reviewer: Gerrit User 1081223 <1081223@85c56323-6fa9-3386-8a01-6480fb634889>