Enable errorprone javacflags by default
While allowlisting rappor-tests module in bp2build to testify its
java_version property is converted to javacopts attribute (aosp/2072296), I ran into a
DoNotCall errorprone error when building `junit` with bazel.

```
ERROR out/soong/workspace/external/junit/BUILD.bazel:9:13: Building
external/junit/libjunit.jar (218 source files) failed: (Exit 1): java
failed: error executing command (from target //external/junit:junit)
../remotejdk11_linux/bin/java -XX:-CompactStrings
'--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED'
'--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ...
(remaining 17 arguments skipped)
external/junit/src/main/java/org/junit/Assert.java:658: error:
[DoNotCall] This method always throws java.lang.AssertionError. Use
assertEquals(String, expected, actual, delta) to compare floating-point
numbers
        assertEquals(null, expected, actual);
	                    ^
			        (see
				https://errorprone.info/bugpattern/DoNotCall)
```

This contradicts with the intention of aosp/1899553 which turned DoNotCall off. Because `errorprone.enabled` is not set to `true`, `DoNotCall:OFF` being applied or not depends on whether RUN_ERROR_PRONE is true.

The error log from `bazel build` above confirms that errorprone
is always on in bazel. So we should default to passing
`errorprone.javacflags` to `javac` when `errorprone.enabled` is unset or
set to `true`.

Test: go test ./bp2build/...
Test: m javac-check RUN_ERROR_PRONE=true

Change-Id: I0b17d8dd471635d7fd1cc087ce2d66e00f816d2c