Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Alexander,
> 
> This started giving compilation errors on our r8-wip bot
> 
> Error: Could not find or load main class hs_err_pid%p.log
> 
> see this for the first red build:
> 
> https://android-build.googleplex.com/builds/branch-dashboard/git_r8-wip-dev?build_id=5719830
> 
> FAILED: out/target/common/obj/PACKAGING/core_dex_intermediates/classes.dex
> /bin/bash -c "(rm -f out/target/common/obj/PACKAGING/core_dex_intermediates/classes*.dex out/target/common/obj/PACKAGING/core_dex_intermediates/d8_input.jar ) && (out/soong/host/linux-x86/bin/zip2zip -j -i prebuilts/sdk/current/system/android.jar -o out/target/common/obj/PACKAGING/core_dex_intermediates/d8_input.jar \"**/*.class\" ) && (out/soong/host/linux-x86/bin/d8 -JXms16M -JXmx2048M -JXX:OnError='cat hs_err_pid%p.log' -JXX:CICompilerCount=6 -JXX:+UseDynamicNumberOfGCThreads --output out/target/common/obj/PACKAGING/core_dex_intermediates/  --min-api 1000   out/target/common/obj/PACKAGING/core_dex_intermediates/d8_input.jar ) && (rm -f out/target/common/obj/PACKAGING/core_dex_intermediates/d8_input.jar )"
> Error: Could not find or load main class hs_err_pid%p.log
> Caused by: java.lang.ClassNotFoundException: hs_err_pid%p.log

You probably need an equivalent change to https://android-review.googlesource.com/c/platform/prebuilts/r8/+/1011544 somewhere, where does that branch get the d8 shell script from?

Patch-set: 1