Allow "-x assembler-with-cpp" in cflags
In pvmfw (packages/modules/Virtualization/pvmfw), we preprocess (-E) a
*.dts file to do the macro expansion of ARM-specific symbols like
GIC_SPI. The *.dts file is not a correct C/C++ source file because it
has texts like `#address-cells = <2>;`.

When compiled with just -E:

error: invalid preprocessing directive
        #address-cells = <2>;

"-x assembler-with-cpp" is to override the language of the input file;
it is reconigized as an assembly code containing C preprocessor
directives.

Note that changing the file suffix to .S is not enough as shown below.

out.S:13:1: error: unexpected token at start of statement
/dts-v1/;

Thus adding "-x assembler-with-cpp" to the allow list.

Bug: N/A
Test: m pvmfw_img
Change-Id: Ia15d39b5600518b0b68793c1c7cf74f0577f54a6