Update patch set 7
Patch Set 7: Presubmit-Ready+1

> Patch Set 7: Presubmit-Ready+1
> 
> > > --- FAIL: TestApexWithStubs (0.08s)
> > apex_test.go:100: Android.bp:2:3: module "myapex" variant "android_common_myapex": module source path manifest.json does not exist
> Sees to be built with old source. Retrying.

Maybe this is due to "--incremental" ? This was successful with my local copy of internal master. 

Adding dwillemsen@.

Patch-set: 7
Reviewer: Gerrit User 1074628 <1074628@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1132673 <1132673@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1