Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> My understanding is that if sourcepath is not specified, then javac will happily find sources in the classpath and compile them.  We don't want javac to be finding any source files at all that are not specified on the command line.  Is there some way to get javac 9 to do that?

If my assumption is correct that javac 8 interprets the "" the same way as the ., then this CL should make not difference? I'm not certain though if that is happening, I was guessing that that is what you had tried to achieve because that is how -classpath would behave.

If you were planning to not have any sourcepath at all, then I don't think it's supported by javac 9; at least that's how I interpret the following error that, before this CL, it prints for each .java file given on the command line:

   error: file should be on source path, or on patch path for module

Why would javac be "finding any source files at all that are not specified on the command line"? My understanding is that javac never compiles source files that aren't given on the command line (either by package name or by file path), is that not correct?

Patch-set: 1
Reviewer: Gerrit User 1103203 <1103203@85c56323-6fa9-3386-8a01-6480fb634889>