Update patch set 3
Patch Set 3:

Hi,

looks like the CL broke some of the Brillo boards in AOSP - the error is in [1]. Reverting this change fixes it. Is there a better way to fix the problem though?

Thanks!

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=6.0.1
TARGET_PRODUCT=edison
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=x86
TARGET_ARCH_VARIANT=silvermont
TARGET_CPU_VARIANT=
TARGET_2ND_ARCH=
TARGET_2ND_ARCH_VARIANT=
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-3.13.0-91-generic-x86_64-with-Ubuntu-14.04-trusty
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=MASTER
OUT_DIR=out
============================================
make: Entering directory `/ssd/android'
[1/2] choosing next stage
Choosing primary.ninja.in for next stage
[2/2] bootstrap out/soong/.bootstrap/build.ninja.in
[1/4] soong_build docs out/soong/.bootstrap/docs/soong_build.html
FAILED: out/soong/.bootstrap/bin/soong_build  -t -b out/soong --docs out/soong/.bootstrap/docs/soong_build.html ./Android.bp
error: bionic/benchmarks/Android.bp:54:1: "bionic-benchmarks-glibc" depends on undefined module "libgoogle-benchmark"
ninja: error: rebuilding 'out/soong/build.ninja': subcommand failed
make: *** [run_soong] Error 1
make: Leaving directory `/ssd/android'

#### make failed to build some targets (7 seconds) ####

Patch-set: 3