Update patch set 12
Change has been successfully merged

10 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: genrule/genrule.go
Insertions: 7, Deletions: 3.

@@ -839,7 +839,7 @@
 		return
 	}
 
-	genruleBp2Build(ctx, "$(RULEDIR)")
+	genruleBp2Build(ctx)
 }
 
 // GenruleBp2Build is used for genrule.
@@ -854,10 +854,10 @@
 		return
 	}
 
-	genruleBp2Build(ctx, "$(GENDIR)")
+	genruleBp2Build(ctx)
 }
 
-func genruleBp2Build(ctx android.TopDownMutatorContext, genDir string) {
+func genruleBp2Build(ctx android.TopDownMutatorContext) {
 	m, _ := ctx.Module().(*Module)
 	// Bazel only has the "tools" attribute.
 	tools_prop := android.BazelLabelForModuleDeps(ctx, m.properties.Tools)
@@ -876,6 +876,10 @@
 	if m.properties.Cmd != nil {
 		cmd = strings.Replace(*m.properties.Cmd, "$(in)", "$(SRCS)", -1)
 		cmd = strings.Replace(cmd, "$(out)", "$(OUTS)", -1)
+		genDir := "$(GENDIR)"
+		if ctx.ModuleType() == "cc_genrule" {
+			genDir = "$(RULEDIR)"
+		}
 		cmd = strings.Replace(cmd, "$(genDir)", genDir, -1)
 		if len(tools.Value.Includes) > 0 {
 			cmd = strings.Replace(cmd, "$(location)", fmt.Sprintf("$(location %s)", tools.Value.Includes[0].Label), -1)
```
```
The name of the file: android/bazel.go
Insertions: 10, Deletions: 10.

@@ -271,16 +271,16 @@
 	// Per-module denylist to opt modules out of mixed builds. Such modules will
 	// still be generated via bp2build.
 	mixedBuildsDisabledList = []string{
-		"libbrotli",           // http://b/198585397, ld.lld: error: bionic/libc/arch-arm64/generic/bionic/memmove.S:95:(.text+0x10): relocation R_AARCH64_CONDBR19 out of range: -1404176 is not in [-1048576, 1048575]; references __memcpy
-		"libc++fs",            // http://b/198403271, Missing symbols/members in the global namespace when referenced from headers in //external/libcxx/includes
-		"libc++_experimental", // http://b/198403271, Missing symbols/members in the global namespace when referenced from headers in //external/libcxx/includes
-		"libc++_static",       // http://b/198403271, Missing symbols/members in the global namespace when referenced from headers in //external/libcxx/includes
-		"libc++abi",           // http://b/195970501, cc_library_static, duplicate symbols because it propagates libc objects.
-		"libc++demangle",      // http://b/195970501, cc_library_static, duplicate symbols because it propagates libc objects.
-		"func_to_syscall_nrs",
-		"libseccomp_policy_app_zygote_sources",
-		"libseccomp_policy_app_sources",
-		"libseccomp_policy_system_sources",
+		"libbrotli",                            // http://b/198585397, ld.lld: error: bionic/libc/arch-arm64/generic/bionic/memmove.S:95:(.text+0x10): relocation R_AARCH64_CONDBR19 out of range: -1404176 is not in [-1048576, 1048575]; references __memcpy
+		"libc++fs",                             // http://b/198403271, Missing symbols/members in the global namespace when referenced from headers in //external/libcxx/includes
+		"libc++_experimental",                  // http://b/198403271, Missing symbols/members in the global namespace when referenced from headers in //external/libcxx/includes
+		"libc++_static",                        // http://b/198403271, Missing symbols/members in the global namespace when referenced from headers in //external/libcxx/includes
+		"libc++abi",                            // http://b/195970501, cc_library_static, duplicate symbols because it propagates libc objects.
+		"libc++demangle",                       // http://b/195970501, cc_library_static, duplicate symbols because it propagates libc objects.
+		"func_to_syscall_nrs",                  // http://b/200899432, bazel-built cc_genrule does not work in mixed build when it is a dependency of another soong module.
+		"libseccomp_policy_app_zygote_sources", // http://b/200899432, bazel-built cc_genrule does not work in mixed build when it is a dependency of another soong module.
+		"libseccomp_policy_app_sources",        // http://b/200899432, bazel-built cc_genrule does not work in mixed build when it is a dependency of another soong module.
+		"libseccomp_policy_system_sources",     // http://b/200899432, bazel-built cc_genrule does not work in mixed build when it is a dependency of another soong module.
 	}
 
 	// Used for quicker lookups
```


Patch-set: 12
Status: merged
Tag: autogenerated:gerrit:merged
Reviewer: Gerrit User 1318142 <1318142@85c56323-6fa9-3386-8a01-6480fb634889>
Label: SUBM=+1
Submission-id: 1829492
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~PrologRule
Submitted-with: MAY: Build-Cop-Override
Submitted-with: MAY: Presubmit-Verified-Together
Submitted-with: MAY: Bypass-Presubmit
Submitted-with: MAY: Presubmit-Ready
Submitted-with: MAY: Autosubmit
Submitted-with: MAY: Exempt
Submitted-with: MAY: Global-Approval
Submitted-with: OK: Code-Review: Gerrit User 1514900 <1514900@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Verified
Submitted-with: MAY: Open-Source-Licensing
Submitted-with: MAY: Lint
Submitted-with: OK: Presubmit-Verified: Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: OK: Non-Author-Code-Review: Gerrit User 1514900 <1514900@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: OK
Submitted-with: Rule-Name: code-owners~CodeOwnerSubmitRule
Attention: {"person_ident":"Gerrit User 1726181 \u003c1726181@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1318142 \u003c1318142@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1074628 \u003c1074628@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}