Emit a better error message in manifest_check.py.
Bug: 132357300
Test: lunch aosp_cf_x86_64_phone-userdebug && m
Test: temporarily patch Gallery2 to fail the check, observe the error:

  error: mismatch in the <uses-library> tags between the build system and the manifest:
    - required libraries in build system: []
                     vs. in the manifest: []
    - optional libraries in build system: [org.apache.http.legacy]
                     vs. in the manifest: [com.google.android.media.effects, org.apache.http.legacy]
    - tags in the manifest (out/soong/.intermediates/packages/apps/Gallery2/Gallery2/android_common/manifest_merger/AndroidManifest.xml):
        <uses-library android:name="com.google.android.media.effects" android:required="false"/>
        <uses-library android:name="org.apache.http.legacy" android:required="false"/>

  note: the following options are available:
    - to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
    - to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
    - to fix the check, make build system properties coherent with the manifest
    - see build/make/Changes.md for details

Change-Id: Id67e359188396f68dcecd8b3f4d1bc26271af56d