Update patch set 1
Patch Set 1: Verified-1

This doesn't work because the link type checks are not accurate.  We are counting lots of libraries as platform that shouldn't be, including core-oj, core-libart, and core.current.stubs.  We currently have no way to mark a library as core except sdk_version: "core_current", which can't be set on core.current.stubs or any of its dependencies.

We could reuse no_standard_libs/no_framework_libs to imply core, but turning that on surfaces a bunch of other mismatches between libraries that are currently marked no_framework_libs and dependencies that are not:
error: frameworks/base/proto/Android.bp:1:1: module "framework-protos" variant "android_common": compiles against core Java API, but dependency "libprotobuf-java-nano" is compiling against non-core Java APIs.Adjust sdk_version: property of the source or target module so that target module is built with the same or smaller API set than the source.

Patch-set: 1
Reviewer: Gerrit User 1132673 <1132673@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1002751 <1002751@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=-1