Update patch set 1
Patch Set 1:

that's odd...

fatal error: 'android/binder_stability.h' file not found
#include <android/binder_stability.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

we're building these with `-target armv7a-linux-androideabi10000`?

[8363/10713] PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r365631b/bi
n/clang++ -c -Isystem/tools/aidl -mthumb -Os -fomit-frame-pointer -DANDROID -fme
ssage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-pr
efixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasi
ng -Werror=date-time -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__
builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -fexper
imental-new-pass-manager -Wno-reserved-id-macro -Wno-unused-command-line-argumen
t -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-
defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-section
s -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,
--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werro
r=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-securit
y -nostdlibinc -msoft-float -march=armv8-a -mfloat-abi=softfp -mfpu=neon-fp-armv
8 -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -D__ARM_FEATURE_LPAE=1 -Iexternal/jsoncpp
/include -Iout/soong/.intermediates/system/tools/aidl/aidl_test_loggable_interfa
ce_ndk-ndk-source/gen/include -isystem prebuilts/ndk/current/sources/cxx-stl/llv
m-libc++/include -isystem prebuilts/ndk/current/sources/cxx-stl/llvm-libc++abi/i
nclude -isystem out/soong/ndk/sysroot/usr/include -isystem out/soong/ndk/sysroot
/usr/include/arm-linux-androideabi -Wall -Werror -Wextra-semi -Wextra -Wall -Wer
ror -target armv7a-linux-androideabi10000 -Bprebuilts/gcc/linux-x86/arm/arm-linu
x-androideabi-4.9/arm-linux-androideabi/bin -DANDROID_STRICT -fPIC -std=gnu++17 
-Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negat
ive -Wno-gnu-include-next -fvisibility-inlines-hidden -fno-rtti  -Werror=int-to-
pointer-cast -Werror=pointer-to-int-cast -Werror=fortify-source -Werror=address-
of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautolo
gical-type-limit-compare -MD -MF out/soong/.intermediates/system/tools/aidl/aidl
_test_loggable_interface_ndk-ndk/android_arm_armv8-a_cortex-a73_core_static/obj/
.intermediates/system/tools/aidl/aidl_test_loggable_interface_ndk-ndk-source/gen
/android/aidl/loggable/ILoggableInterfaceNdk.o.d -o out/soong/.intermediates/sys
tem/tools/aidl/aidl_test_loggable_interface_ndk-ndk/android_arm_armv8-a_cortex-a
73_core_static/obj/.intermediates/system/tools/aidl/aidl_test_loggable_interface
_ndk-ndk-source/gen/android/aidl/loggable/ILoggableInterfaceNdk.o out/soong/.int
ermediates/system/tools/aidl/aidl_test_loggable_interface_ndk-ndk-source/gen/and
roid/aidl/loggable/ILoggableInterfaceNdk.cpp

does the "current" or "system_current" in system/tools/aidl/build/aidl_interface.go mean 10000? that's unfortunate, because that means the build system has a different definition of __ANDROID_NDK__ to the NDK/bionic itself... __ANDROID_NDK__ basically means "not 10000".

Patch-set: 1
Reviewer: Gerrit User 1003224 <1003224@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0