Update patch set 3
Change has been successfully merged

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: android/bazel.go
Insertions: 2, Deletions: 0.

@@ -141,6 +141,7 @@
 		"build/bazel/bazel_skylib":/* recursive = */ true,
 		"build/bazel/rules":/* recursive = */ true,
 		"build/bazel/rules_cc":/* recursive = */ true,
+		"build/bazel/scripts":/* recursive = */ true,
 		"build/bazel/tests":/* recursive = */ true,
 		"build/bazel/platforms":/* recursive = */ true,
 		"build/bazel/product_variables":/* recursive = */ true,
@@ -238,6 +239,7 @@
 	// Per-module denylist to opt modules out of mixed builds. Such modules will
 	// still be generated via bp2build.
 	mixedBuildsDisabledList = []string{
+		"libc++_static",  // "error: no member named 'signbit' in the global namespace; did you mean 'sigwait'?"
 		"libc++abi",      // http://b/195970501, cc_library_static, duplicate symbols because it propagates libc objects.
 		"libc++demangle", // http://b/195970501, cc_library_static, duplicate symbols because it propagates libc objects.
 	}
```


Patch-set: 3
Status: merged
Tag: autogenerated:gerrit:merged
Reviewer: Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Label: SUBM=+1
Submission-id: 1814446
Submitted-with: OK
Submitted-with: MAY: Build-Cop-Override
Submitted-with: MAY: Presubmit-Verified-Together
Submitted-with: MAY: Bypass-Presubmit
Submitted-with: MAY: Presubmit-Ready
Submitted-with: MAY: Autosubmit
Submitted-with: MAY: Exempt
Submitted-with: MAY: Global-Approval
Submitted-with: OK: Code-Review: Gerrit User 1066075 <1066075@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Verified
Submitted-with: MAY: Open-Source-Licensing
Submitted-with: MAY: Lint
Submitted-with: MAY: Presubmit-Verified
Submitted-with: OK: Non-Author-Code-Review: Gerrit User 1066075 <1066075@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: OK
Attention: {"person_ident":"Gerrit User 1726181 \u003c1726181@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1514900 \u003c1514900@85c56323-6fa9-3386-8a01-6480fb634889\u003e","operation":"REMOVE","reason":"Change was submitted"}