Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 1:
> > 
> > Jiyong, I am getting an error with this change:
> > 
> > error: frameworks/opt/net/ike/apex/Android.bp:25:1: module "com.android.ipsec" variant "android_common_com.android.ipsec_image": Dependency android.net.ipsec.ike of updatable module must use stable SDK, found non stable SDK private_(no version)
> > 
> > android.net.ipsec.ike is java_sdk_library that has sdk_version: "module_current". I am not sure if sdk_Version is not being propagated to the impl java.Library, or I am doing something wrong. Any ideas?
> 
> You used type-switch which misses java_sdk_library module's type: SdkLibrary.
> 
> How about something like ..
> 
>   if m, ok := module.(interface {CheckStableSdkVersion() error}); ok {
> 	if err := m.CheckStableSdkVersion(); err != nil {
> 		..
> 
> You may want to put the method in ApexModule interface.

You are right.. I assumed the dep would be on the underlying *java.Library.

I don't think it belongs to ApexModule? Would it return "true" for cc_library and genrule that implement ApexModule?

Should I rather export SdkSpec / SdkContext and use that? What we really want is for anyone who implements SdkContext to have this check in there. (Ideally, we would also have commonSdkProperties shared in all places if possible).

Patch-set: 2