Revert "Add minijail to whitelist.go"
Revert submission 1240232-aosp-minijail-as-rust-crate

Reason for revert: b/149981813
error: external/minijail/Android.bp:419:1: module "libminijail_sys"
variant "darwin_x86_64_rlib": depends on disabled module "libminijail"
ninja: build stopped: subcommand failed.
04:30:19 soong bootstrap failed with: exit status 1
Return Code: 1
Reverted Changes:
I2231149f1:Add minijail to whitelist.go
I15cc9b3e4:Allow minijail to be built as an Android Rust libr...

Bug: 149981813
Change-Id: Idd546468b94d9be4b29f05fe8c8669715b9578e0