Update patch set 4
Patch Set 4:

The tests failed and I can't work out why. I get the following error:

FAILED: out/soong/.bootstrap/soong-sdk/test/test.passed
out/soong/.bootstrap/bin/gotestrunner -p ./build/soong/sdk -f out/soong/.bootstrap/soong-sdk/test/test.passed -- out/soong/.bootstrap/soong-sdk/test/test -test.short
--- FAIL: TestBasicSdkWithDroidstubs (0.03s)
    sdk_test.go:121: Android.bp:28:3: module "myjavalib" variant "android_common": missing dependency on "mystub", is the property annotated with android:"path"?
FAIL

Patch-set: 4
Reviewer: Gerrit User 1039338 <1039338@85c56323-6fa9-3386-8a01-6480fb634889>